default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>

development:
  <<: *default
  database: relay_help_development

test:
  <<: *default
  database: relay_help_test

production:
  <<: *default
  database: relay_help_production
  url: <%= ENV["DATABASE_URL"] %>